spring:
  application:
    name: yu-ai-agent
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

# LangChain4j 配置
langchain4j:
  dashscope:
    api-key: placeholder
  ollama:
    base-url: http://localhost:11434
    chat-model: qwen2.5:3b
    embedding-model: bge-large

# MCP Server 配置
mcp:
  server:
    url: http://localhost:8127
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yupi.yuaiagent.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchAPI
search-api:
  # 需要替换为你自己的 key
  api-key: placeholder

# Pexels API
pexels:
  api-key: placeholder
# 修改日志级别，查看 LangChain4j 更多调用细节
logging:
  level:
#    dev.langchain4j: DEBUG
#    dev.langchain4j.model.ollama: DEBUG
    dev.langchain4j: INFO
    dev.langchain4j.model.ollama: INFO